# Benchmark Configuration for Hyperlinkr
# Use this config for performance testing to bypass rate limits

environment = "benchmark"
database_urls = ["redis://localhost:6379"]
base_url = "http://localhost:3000"
app_port = 3000
rust_log = "info"  # Reduce logging overhead during benchmarks

[cache]
l1_capacity = 50000          # Increased for benchmark
l2_capacity = 500000         # Increased for benchmark
bloom_bits = 2097152         # Doubled for better performance
bloom_expected = 200000      # Higher expected load
bloom_shards = 16            # More shards for concurrency
bloom_block_size = 256       # Larger blocks
redis_pool_size = 32         # More connections for load testing
ttl_seconds = 7200           # Longer TTL to reduce evictions
max_failures = 10            # Higher tolerance during load testing
retry_interval_secs = 10      # Changed to meet minimum requirement
redis_command_timeout_secs = 3     # Longer timeout under load
redis_max_feed_count = 500   # Higher feed count
redis_broadcast_channel_capacity = 64  # Larger channel
redis_max_command_attempts = 5     # More attempts
redis_connection_timeout_ms = 15000   # Longer connection timeout
redis_reconnect_max_attempts = 5
redis_reconnect_delay_ms = 100
redis_reconnect_max_delay_ms = 1000
sled_path = "./data/cache.sled"
sled_cache_bytes = 134217728   # 128MB cache
sled_flush_ms = 600000         # Less frequent flushes during benchmarks
sled_snapshot_ttl_secs = 10
sled_compression = true
use_sled = true
geoip_mmdb_path = "./geo/GeoLite2-City.mmdb"
geo_sled_path = "./data/geo.sled"
geo_hot_capacity = 500000      # Much larger geo cache
geo_ttl_seconds = 7200         # Longer geo cache TTL
geo_evict_interval_secs = 120  # Less frequent eviction

[rate_limit]
# Effectively disabled for benchmarking
shorten_requests_per_minute = 100000      # Very high limit
redirect_requests_per_minute = 1000000    # Very high limit

[codegen]
shard_bits = 14              # More shards for higher concurrency (16K shards)
max_attempts = 3             # Fewer attempts to reduce latency

[storage]
sled_path = "./data/storage.sled"
sled_cache_bytes = 268435456   # 256MB storage cache
sled_flush_ms = 600000         # Less frequent flushes
sled_snapshot_ttl_secs = 10
sled_compression = true

[analytics]
flush_interval_ms = 1000       # Less frequent analytics flushing
batch_size = 50_000           # Larger batches
max_batch_size_ms = 5_000     # Higher timeout
max_batch_size = 50_000       # Larger max batch
sled_path = "./data/analytics.sled"

[security]
global_admins = []
jwt_secret = "0ecEuxack4XAdudiWTWXT3UocVEFhPZBaE0PhIJk3M3PNIfk5BnM+1WSYb0PaPaDCpApBRCPmrH89wDJNjQdyvkl6rEHoebJbmnYf+GqHA2WM6LqhNG+LCAHke8NFRnnlyHEhvr3KiJpQSKR0yWA8jqENpdLjVury+OknAJvQptoANSdIY8uF0FXU0kHLpnxdJ9HXRdyH0A3NTYX+EP9x8Jo3G5ymweJdLp/KUSHBjJGnAsHZAWlg9bOrqIEjau1VwUdDuFrv7yRMZYLBQsa6MRCZ09eRABl5MvqBMs/B8O3tYwUKeP04GqxwI2k5mk2qgMBPpij/zi5iKhDQ=="
token_expiry_secs = 86400
domain = "localhost"
subdomains = ["api"]
