environment = "development"
database_urls = ["redis://localhost:6379"]
base_url = "http://localhost:3000"
app_port = 3000
rust_log = "debug"

[cache]
l1_capacity = 10000
l2_capacity = 100000
bloom_bits = 1048576
bloom_expected = 100000
bloom_shards = 8
bloom_block_size = 128
redis_pool_size = 8
ttl_seconds = 3600
max_failures = 5
retry_interval_secs = 10
redis_command_timeout_secs = 1
redis_max_feed_count = 200
redis_broadcast_channel_capacity = 32
redis_max_command_attempts = 3
redis_connection_timeout_ms = 10000
redis_reconnect_max_attempts = 3
redis_reconnect_delay_ms = 100
redis_reconnect_max_delay_ms = 500
sled_path = "./data/cache.sled"
sled_cache_bytes = 67108864
sled_flush_ms = 300000
sled_snapshot_ttl_secs = 5
sled_compression = true
use_sled = true
geoip_mmdb_path = "./geo/GeoLite2-City.mmdb"
geo_sled_path = "./data/geo.sled"
geo_hot_capacity = 200000
geo_ttl_seconds = 3600
geo_evict_interval_secs = 60

[rate_limit]
shorten_requests_per_minute = 10
redirect_requests_per_minute = 1_000

[codegen]
shard_bits = 12
max_attempts = 5

[storage]
sled_path = "./data/storage.sled"
sled_cache_bytes = 67108864
sled_flush_ms = 300000
sled_snapshot_ttl_secs = 5
sled_compression = true

[analytics]
flush_interval_ms = 200
batch_size = 10_000
max_batch_size_ms = 1_000
max_batch_size = 10_000
sled_path = "./data/analytics.sled"

[security]
global_admins = []
jwt_secret = "0ecEuxack4XAdudiWTWXT3UocVEFhPZBaE0PhIJk3M3PNIfk5BnM+1WSYb0PaPaDCpApBRCPmrH89wDJNjQdyvkl6rEHoebJbmnYf+GqHA2WM6LqhNG+LCAHke8NFRnnlyHEhvr3KiJpQSKR0yWA8jqENpdLjVury+OknAJvQptoANSdIY8uF0FXU0kHLpnxdJ9HXRdyH0A3NTYX+EP9x8Jo3G5ymweJdLp/KUSHBjJGnAsHZAWlg9bOrqIEjau1VwUdDuFrv7yRMZYLBQsa6MRCZ09eRABl5MvqBMs/B8O3tYwUKeP04GqxwI2k5mk2qgMBPpij/zi5iKhDQ="
token_expiry_secs = 86400
domain = "localhost"
subdomains = ["api"]