environment = "development"
database_urls = ["redis://dragonfly:6379"]
base_url = "http://localhost:3000"
app_port = 3000
rust_log = "debug"

[cache]
l1_capacity = 10000
l2_capacity = 100000
bloom_bits = 1048576
bloom_expected = 100000
bloom_shards = 8
bloom_block_size = 128
redis_pool_size = 8
ttl_seconds = 3600
max_failures = 5
retry_interval_secs = 10
redis_command_timeout_secs = 1
redis_max_feed_count = 200
redis_broadcast_channel_capacity = 32
redis_max_command_attempts = 3
redis_connection_timeout_ms = 10000
redis_reconnect_max_attempts = 3
redis_reconnect_delay_ms = 100
redis_reconnect_max_delay_ms = 500

[rate_limit]
shorten_requests_per_minute = 10
redirect_requests_per_minute = 1_000

[codegen]
shard_bits = 12
max_attempts = 5

[analytics]
flush_interval_ms = 200
batch_size = 10_000
max_batch_size_ms = 1_000
max_batch_size = 10_000