services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "${DRAGONFLY_PORT:-6379}:6379"
    volumes:
      - dragonfly_data:/data
    command:
      - dragonfly
      - --maxmemory=${DRAGONFLY_MAXMEMORY:-1250mb}
      - --cache_mode=${DRAGONFLY_CACHE_MODE:-true}
      - --snapshot_cron=${DRAGONFLY_SNAPSHOT_CRON:-* * * * *}
      - --nodf_snapshot_format
      - --dbfilename=${DRAGONFLY_DBFILENAME:-dump.df}
      - --bind=${DRAGONFLY_BIND:-0.0.0.0}
      - --port=${DRAGONFLY_PORT:-6379}
      - --proactor_threads=${DRAGONFLY_PROACTOR_THREADS:-2}
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 2s
      retries: 3

  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - COMPOSE_BAKE=${COMPOSE_BAKE:-true}
    depends_on:
      dragonfly:
        condition: service_healthy

volumes:
  dragonfly_data:
