version: '3.8'

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: hyperlinkr-dragonfly
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data
    command:
      - dragonfly
      - --bind=0.0.0.0
      - --port=6379
      - --maxmemory=2048mb
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - hyperlinkr-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hyperlinkr-app
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=benchmark
      - RUST_LOG=warn
    volumes:
      - app_data:/app/data
      - ./config.benchmark.toml:/app/config.benchmark.toml:ro
    depends_on:
      dragonfly:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - hyperlinkr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dragonfly_data:
    driver: local
  app_data:
    driver: local

networks:
  hyperlinkr-network:
    driver: bridge
